Carpeta nueva añadida
CarsOk/proyecto-formativo-cinyuje pull request #16
Opened 2021-09-02 13:22 UTC by sugeyberdugo

Se añade nueva carpeta "especificar" y se crea un archivo md con información sobre técnicas de recolección de datos. Por favor verificar y aprobar.

2021-09-02 16:03 UTC, Josymargeo2909 approved these changes

2021-09-04 17:53 UTC, JoseFuentes23 requested changes
Hello @sugeyberdugo  I was reviewing your work , and I found an error in the writing , in line number 33 . Please verify and resend with the solution . Thanks

2021-09-04 19:18 UTC, sugeyberdugo commented
@JoseFuentes23 @Josymargeo2909 the line was modified. Thanks for your review

2021-09-04 23:42 UTC, JoseFuentes23 approved these changes

2021-09-05 16:21 UTC, merged