se realiza planilla stakeholders
CarsOk/proyecto-formativo-cinyuje pull request #30
Opened 2021-09-14 03:34 UTC by Josymargeo2909

compañeros aquí planteo la tarea individual de los stakeholders yel link de las hojas de vida revisar por favor

2021-09-18 22:41 UTC, sugeyberdugo commented on stakeholders/readme.md
> +| 05 | DIAN | Regulador y vigilado de procesos legales | Medio | Via legal |
The company doesn't have billing. DIAN isn't stakeholder.

2021-09-18 22:45 UTC, sugeyberdugo commented
Hello classmate @Josymargeo2909  check the comment and update. Please fix the index part and save the stakeholder file inside "Especificar". Thanks!

2021-09-19 17:50 UTC, JoseFuentes23 requested changes
revisar por favor y volver a enviar

2021-09-23 17:59 UTC, JoseFuentes23 requested changes
@Josymargeo2909  por favor revisar la redacción (que brinde solution)

2021-09-29 23:18 UTC, closed without merging